name: lone
age: 25
address: "myway num1"
active: true
key:
  key1: value1
  key2: value2
  key3: value3
jsonObject: { key: value, key2: value2, key3: value3 }
jobArray:
  -item1
  -item2
  -item3
myArry:
    -item1
    -item2
    -item3
longText: >
  asdflj dasfjkéad dsfjkél
  asdjfélasdj
  adsfjkléa
nolfText:
  lasdfjdasl adsf
  ls -a
  pwd